version: '3.3' # must be compatible with installed version on tux-devop-test
services:
  hello-world:
    image: hello-world:1.0
    ports: 
      - 8080:8080
    environment:
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypass
      DATABASE_URL: "jdbc:postgresql://postgres:5432/mydb"
  postgres:
    image: postgres:10.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
volumes:
  postgres-data: